### ISSUE TITLE
Missing 'improve_sample_id' for some cell-lines

### ISSUE THREAD

**Issue by priyanka9991** [PNNL-CompBio/candleDataProcessing#10]
When trying to map DepMap ID to RRID for the CCLE Multiomics data, I found some cell-lines with missing RRID. Then I used the 'samples.csv' file in this folder: candleDataProcessing/data/ to map the DepMap ID to 'improve_sample_id' for those cell-lines with missing RRIDs. However, there are still some cell lines with no improve id as well. I am attaching a list of cell-lines with no RRID and no 'improve_sample_id'.
![missing_rrid_imp_id](https://user-images.githubusercontent.com/86702829/235536471-26d6fc4b-0c92-4b77-a010-18aa24be244e.png)

**Comment by sgosline** [comment]
Hi @priyanka9991 ,

I checked the sample file and found that theses samples have an improve_sample_id, shown below. Are you using the up-to-date samples.csv file? 

![Screenshot 2023-05-02 at 9 43 02 AM](https://user-images.githubusercontent.com/1847866/235730646-d5b92f3d-02b3-4215-99f7-92e8876a0cf4.png)

**Comment by sgosline** [comment]
I haven't added cell lines that aren't in cellosaurus or the `data/DepMap_Argonne_Mapping.csv` in this repo. If you can send me the mapping information for these cell lines i can add them.

**Comment by sgosline** [comment]
Update - i'm also using the Model.csv file from depmap, should be using the sample_info.csv file.
