### ISSUE TITLE
Can't seem to find correct files names in HCMI script

### ISSUE THREAD

**Issue by sgosline** [PNNL-CompBio/candleDataProcessing#43]
The HCMI script, using the data collected from the manifest, is failing to find the right files. 

```FileNotFoundError                         Traceback (most recent call last)
Cell In[8], line 1
----> 1 res = get_clean_files('transcriptomics')

Cell In[7], line 52, in get_clean_files(data_type)
     50         dataframe = pd.read_csv(f, delimiter='\t', skiprows=7)
     51 else:
---> 52     dataframe = pd.read_csv(filepath, delimiter='\t')
     54 dataframe['file_id'] = folder_n
     55 dataframe.reset_index(inplace=True)
```

The actual error file is:
```
FileNotFoundError: [Errno 2] No such file or directory: 'transcriptomics_manifest_files/30583b43-653b-430f-ace8-41fda23d3b9d/76ebf3e8-9f7e-4935-b281-bf35ea194c94.rna_seq.augmented_star_gene_counts.tsv'
```

When I look in that directory, i get a different file:
```
$ ls transcriptomics_manifest_files/5dd4f92e-720f-449d-8ead-d29dd528c402/
4831b759-c5dc-40d1-8d0f-b4fc4bc1eb32.rna_seq.augmented_star_gene_counts.tsv logs
```

**Comment by jjacobson95** [comment]
What is the exact python command you run?

**Comment by sgosline** [comment]
WE47023:hcmi gosl241$ python getHCMIData.py -m full_manifest.txt  -t transcriptomics -o transcriptomics.csv

And I also recreated it using ipython and pasting the function directly (i was trying a few hacks to fix it and failed)

**Comment by jjacobson95** [comment]
Ahhh, try the [transcriptomics_gdc_manifest.txt](https://github.com/PNNL-CompBio/candleDataProcessing/blob/JJ_hcmi_branch/hcmi/transcriptomics_gdc_manifest.txt)!

**Comment by sgosline** [comment]
Got it, trying now (and updating the README i'm keeping with commands)
